name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Giver dig den manuelle 'Run workflow' knap på GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    # Cal.com builds kræver meget plads, så vi sikrer os, at GitHub Actions har nok
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: actions/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.render
          platforms: linux/amd64
          push: true
          tags: victorlafargue/allio-booking:v1
          # Vi optimerer hukommelsen til Node under selve buildet
          build-args: |
            NODE_OPTIONS=--max-old-space-size=4096
          # Cache hjælper med at gøre efterfølgende builds hurtigere
          cache-from: type=gha
          cache-to: type=gha,mode=max